"""Configuration constants for Synthetic Quantum GPU."""

DEFAULT_SEED = 42
DEFAULT_MAX_CACHE_ITEMS = 10_000
DEFAULT_MAX_MEMORY_ENTRIES = 100_000
DEFAULT_DIM = 128
DEFAULT_TOP_K = 8
DEFAULT_BATCH_SIZE = 32
DEFAULT_MAX_BATCH_SIZE = 1024
DEFAULT_MIN_BATCH_SIZE = 4
